---
development:
  cloud_name: 
  api_key: ''
  api_secret: 
  enhance_image_tag: true
  static_image_support: false
  secure: true
production:
  cloud_name: 
  api_key: ''
  api_secret: 
  enhance_image_tag: true
  static_image_support: true
  secure: true
test:
  cloud_name: 
  api_key: ''
  api_secret: 
  enhance_image_tag: true
  static_image_support: false
  secure: true
